# Generated by Django 3.2.7 on 2021-09-07 16:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Тема')),
                ('classroom', models.SmallIntegerField(verbose_name='Класс')),
                ('subject', models.CharField(choices=[('al', 'Алгебра'), ('as', 'Астрономия'), ('bi', 'Биология'), ('ch', 'Химия'), ('en', 'Английский'), ('gm', 'Геометрия'), ('hi', 'История'), ('ph', 'Физика'), ('ru', 'Русский язык'), ('cs', 'Информатика'), ('ss', 'Обществознание'), ('gg', 'География'), ('fl', 'Иностранный язык'), ('li', 'Литература'), ('ob', 'ОБЖ')], max_length=2, verbose_name='Предмет')),
                ('description', models.TextField(verbose_name='Описание')),
                ('publish_time', models.DateTimeField(auto_now_add=True, verbose_name='Время публикации')),
                ('edit_time', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
                ('is_show', models.BooleanField(verbose_name='Видимость')),
            ],
            options={
                'verbose_name': 'Контрольная',
                'verbose_name_plural': 'Контрольные',
                'ordering': ('publish_time',),
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_teacher',
            field=models.BooleanField(default=1, verbose_name='Учитель'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Вопрос')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='api.exam', verbose_name='Упражнение')),
            ],
            options={
                'verbose_name': 'Задание',
                'verbose_name_plural': 'Задания',
            },
        ),
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.SmallIntegerField(verbose_name='Количество набранных баллов')),
                ('total', models.SmallIntegerField(verbose_name='Общее количество баллов')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='Начало выполнения')),
                ('end_time', models.DateTimeField(auto_now=True, verbose_name='Конец выполнения')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='api.exam', verbose_name='Упражнение')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Статистика',
                'verbose_name_plural': 'Статистика',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(upload_to='user/', verbose_name='Аватарка')),
                ('classroom', models.SmallIntegerField(verbose_name='Класс')),
                ('letter', models.CharField(max_length=1, verbose_name='Буква класса')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
        migrations.AddField(
            model_name='exam',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to=settings.AUTH_USER_MODEL, verbose_name='Учитель'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='Комментатор')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.exam', verbose_name='Упражнение')),
            ],
            options={
                'verbose_name': 'Комметарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Вариант ответа')),
                ('is_correct', models.BooleanField(verbose_name='Верный')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='api.task', verbose_name='Ответ')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
            },
        ),
    ]
