# Generated by Django 3.2.7 on 2021-09-07 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210907_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='is_show',
            field=models.BooleanField(default=True, verbose_name='Видимость'),
        ),
    ]
