# Generated by Django 3.2.7 on 2021-09-09 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_exam_is_show'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Вопрос')),
                ('statistics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errors', to='api.statistics', verbose_name='Ошибки')),
            ],
            options={
                'verbose_name': 'Ошибка',
                'verbose_name_plural': 'Ошибки',
            },
        ),
    ]
