# Generated by Django 3.2.7 on 2021-09-09 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_errorstatistics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='classroom',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='letter',
        ),
    ]
