# Generated by Django 3.2.7 on 2021-09-09 16:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210909_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='edit_time',
            field=models.DateTimeField(auto_now=True, verbose_name='Время редактирования'),
        ),
        migrations.AddField(
            model_name='comment',
            name='publish_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Время публикации'),
            preserve_default=False,
        ),
    ]
