# Generated by Django 3.2.7 on 2021-09-24 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_task_scores'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('publish_time',), 'verbose_name': 'Комметарий', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.AlterModelOptions(
            name='exam',
            options={'ordering': ('-publish_time',), 'verbose_name': 'Контрольная', 'verbose_name_plural': 'Контрольные'},
        ),
        migrations.AlterModelOptions(
            name='statistics',
            options={'ordering': ('-start_time',), 'verbose_name': 'Статистика', 'verbose_name_plural': 'Статистика'},
        ),
        migrations.AlterField(
            model_name='exam',
            name='subject',
            field=models.CharField(choices=[('al', 'Алгебра'), ('as', 'Астрономия'), ('bi', 'Биология'), ('ch', 'Химия'), ('en', 'Английский'), ('gm', 'Геометрия'), ('hi', 'История'), ('ph', 'Физика'), ('ru', 'Русский язык'), ('cs', 'Информатика'), ('ss', 'Обществознание'), ('gg', 'География'), ('fl', 'Иностранный язык'), ('li', 'Литература'), ('ob', 'ОБЖ'), ('dp', 'Другой предмет')], max_length=2, verbose_name='Предмет'),
        ),
    ]
